name: Feature request
description: Suggest an idea to improve Helix
title: "[FEATURE] <short description>"
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the feature.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve? Who benefits?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your preferred solution or approach.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or any other context.
