name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cmake ninja-build gcc g++ tar

      - name: Configure (Release)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Package tarball
        run: |
          cd build
          tar -czf helix-linux-amd64.tar.gz helixd helixctl helxcompiler libhelix-core.a libhelix-daemon.a

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/helix-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
